#!/bin/bash
set -e

# Validate Docusaurus site for common issues
# Usage: ./validate.sh [--fix]
# Example: ./validate.sh --fix

FIX_MODE="${1:-}"

echo "Validating Docusaurus site..." >&2

ERRORS=()
WARNINGS=()

# Check for package.json
if [ ! -f "package.json" ]; then
  ERRORS+=("package.json not found - not a valid Docusaurus project")
fi

# Check for docusaurus.config
CONFIG_FILE=""
for file in "docusaurus.config.ts" "docusaurus.config.js"; do
  if [ -f "$file" ]; then
    CONFIG_FILE="$file"
    break
  fi
done

if [ -z "$CONFIG_FILE" ]; then
  ERRORS+=("docusaurus.config.ts/js not found")
else
  echo "Found config: $CONFIG_FILE" >&2
fi

# Check for sidebars
SIDEBAR_FILE=""
for file in "sidebars.ts" "sidebars.js"; do
  if [ -f "$file" ]; then
    SIDEBAR_FILE="$file"
    break
  fi
done

if [ -z "$SIDEBAR_FILE" ]; then
  WARNINGS+=("sidebars.ts/js not found - using autogenerated sidebar")
else
  echo "Found sidebars: $SIDEBAR_FILE" >&2
fi

# Check docs directory
if [ -d "docs" ]; then
  DOC_COUNT=$(find docs -name "*.md" -o -name "*.mdx" | wc -l | tr -d ' ')
  echo "Found $DOC_COUNT documentation files" >&2

  # Check for docs without frontmatter
  MISSING_FRONTMATTER=()
  while IFS= read -r file; do
    if [ -f "$file" ]; then
      FIRST_LINE=$(head -n 1 "$file")
      if [ "$FIRST_LINE" != "---" ]; then
        MISSING_FRONTMATTER+=("$file")
      fi
    fi
  done < <(find docs -name "*.md" -o -name "*.mdx")

  if [ ${#MISSING_FRONTMATTER[@]} -gt 0 ]; then
    WARNINGS+=("${#MISSING_FRONTMATTER[@]} files missing frontmatter")
  fi
else
  WARNINGS+=("docs/ directory not found")
fi

# Check blog directory
if [ -d "blog" ]; then
  BLOG_COUNT=$(find blog -name "*.md" -o -name "*.mdx" | wc -l | tr -d ' ')
  echo "Found $BLOG_COUNT blog posts" >&2

  # Check for authors.yml
  if [ ! -f "blog/authors.yml" ] && [ ! -f "blog/authors.json" ]; then
    WARNINGS+=("blog/authors.yml not found - consider creating one")
  fi
fi

# Check static directory
if [ -d "static" ]; then
  echo "Found static/ directory" >&2

  # Check for favicon
  if [ ! -f "static/img/favicon.ico" ] && [ ! -f "static/favicon.ico" ]; then
    WARNINGS+=("favicon.ico not found in static/")
  fi
else
  WARNINGS+=("static/ directory not found")
fi

# Check src/css directory
if [ -d "src/css" ]; then
  CSS_FILE=""
  for file in "src/css/custom.css" "src/css/custom.scss"; do
    if [ -f "$file" ]; then
      CSS_FILE="$file"
      break
    fi
  done

  if [ -z "$CSS_FILE" ]; then
    WARNINGS+=("custom.css/scss not found in src/css/")
  fi
fi

# Check node_modules
if [ ! -d "node_modules" ]; then
  WARNINGS+=("node_modules not found - run 'npm install'")
fi

# Check .docusaurus cache
if [ -d ".docusaurus" ]; then
  CACHE_SIZE=$(du -sh .docusaurus 2>/dev/null | cut -f1)
  echo "Cache size: $CACHE_SIZE" >&2
fi

# Try to run build check (if npm is available)
if command -v npm &> /dev/null && [ -d "node_modules" ]; then
  echo "Running build validation..." >&2
  if ! npm run build 2>&1 | head -50 > /tmp/docusaurus-build.log; then
    # Check for common errors
    if grep -q "broken" /tmp/docusaurus-build.log; then
      BROKEN_LINKS=$(grep -c "broken" /tmp/docusaurus-build.log || echo "0")
      ERRORS+=("Build failed: $BROKEN_LINKS broken links detected")
    else
      ERRORS+=("Build failed - check npm run build output")
    fi
  else
    echo "Build validation passed" >&2
  fi
fi

# Output results
echo "" >&2
echo "=== Validation Results ===" >&2

ERROR_COUNT=${#ERRORS[@]}
WARNING_COUNT=${#WARNINGS[@]}

if [ $ERROR_COUNT -gt 0 ]; then
  echo "ERRORS ($ERROR_COUNT):" >&2
  for error in "${ERRORS[@]}"; do
    echo "  ❌ $error" >&2
  done
fi

if [ $WARNING_COUNT -gt 0 ]; then
  echo "WARNINGS ($WARNING_COUNT):" >&2
  for warning in "${WARNINGS[@]}"; do
    echo "  ⚠️  $warning" >&2
  done
fi

if [ $ERROR_COUNT -eq 0 ] && [ $WARNING_COUNT -eq 0 ]; then
  echo "✅ All checks passed!" >&2
fi

# Output JSON for agent consumption
cat << EOF
{
  "success": $([ $ERROR_COUNT -eq 0 ] && echo "true" || echo "false"),
  "errors": $ERROR_COUNT,
  "warnings": $WARNING_COUNT,
  "config_file": "${CONFIG_FILE:-null}",
  "sidebar_file": "${SIDEBAR_FILE:-null}",
  "message": "Validation complete with $ERROR_COUNT errors and $WARNING_COUNT warnings"
}
EOF
